Fix various build issues
react-community/react-native-webgl pull request #91
Opened 2019-07-04 05:57 UTC by mars-lan

# Summary
- Update podspec to include the newly added .mm file
- Update main file location in package.json

## Test Plan
Build passes on iOS & Android

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

2019-07-28 22:10 UTC, lidio601 approved these changes

2019-08-08 08:46 UTC, gre requested changes

2019-08-08 08:46 UTC, gre commented on package.json
> +  "main": "src/index.js",
mmh I think the entry point still need to be lib/index.js https://unpkg.com/browse/react-native-webgl@0.8.0/lib/index.js , the babel-compiled version

2019-08-14 14:55 UTC, gre commented
closed by https://github.com/react-native-community/react-native-webgl/commit/906f2fbaaad37b7b643f9147924fb8a16a79521f

2019-08-14 14:55 UTC, closed without merging